"""add bottle_cost and sell_price

Revision ID: 8242123fa7c2
Revises: a4b70471dfbe
Create Date: 2026-10-03 14:59:41.446765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8242123fa7c2'
down_revision: Union[str, Sequence[str], None] = 'a4b70471dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('bottle_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('recipes', sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'sell_price')
    op.drop_column('products', 'bottle_cost')
    # ### end Alembic commands ###
